name: CreateImage

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push container
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Server/Dockerfile
          tags: ghcr.io/koryphaee/nuget-cache:latest
